const quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Don't forget to thank the bus driver",
    "If someone brags, brag right back",
    "superb owl",
    "my code is better than yours",
    "Now, topologically, a dog is a sphere",
    "Why cant Nelly The Hamster use webhooks?????",
    "we do caches by lines",
    "everything u think, WRONG!",
    "You pushed the America button",
    "One of the requirements to start a startup is having no knowledge of code",
    "Water from the nile",
    "why does my slack channel not have party parrot?",
    "javascript was built in a day",
    "I'm not a robot",
    "It's Daffy Duck, NOT Donald Duck!",
    "Sometimes you gotta close a door to open a window",
    "somebody hire me already!",
    "so what does your bedrock look like?",
    "Remember to wear sunscreen",
    "I know a guy",
    "Look at all those kings!",
    "i'm gonna have to bench on this thought",
    "CHANGE NIKE, CHANGE WALLSTREET, CHANGE THE WORLD!",
    "I own Top Gun on DVD do not mess with me",
    "Get Stallman on the phone",
    "teach him to do nothing but Naruto run",
    "i'm eating pizza roles rn",
    "instagram in the middle attack",
    "button your god damn shirt up!",
    "Push START to open the MENU!",
    "i need the electrolytes for my tantrums",
    "C++ with Bob Ross",
    "You know I'm down with TDD",
    "The worlds greatest artist are on RCA Victor Records",
    "I always knew that one day, they'd try to bring me down",
    "All the nightmares came today, And it looks as though they're here to stay",
    "If you get out of bed, And find me standing all alone, Open-eyed, Burn the page, My little dark age",
    "Don't you have somewhere to be at seven thirty?",
    "I personally wouldn't use Ruby to pilot a spacecraft",
    "The correct spelling is SCHOOL, not SCHOOL. Some people put the second O before the first O which is absolutely wrong.",
    "We live in a JRPG",
    "Java is the gateway to hell",
    "I hear channel 62 is pretty good",
    "Laugh about it, shout about it when you've got to choose, Every way you look at this you lose",
    "One step closer to my own personal hell!",
    "weapons was good",
    "Do not operate with wet hands",
    "All hand prepare for multi-ball!",
    "Fascinating!",
    "Hailing frequencies open, Captain.",
    "I'm a doctor, not a script writer!",
    "You cannot change the laws of physics, Captain; I've got to have thirty minutes!",
    "One, seven, three, four, six, seven, three, two, one, four, seven, six, Charlie, three, two, seven, eight, nine, seven, seven, seven, six, four, three, Tango, seven, three, two, Victor, seven, three, one, one, seven, eight, eight, eight, seven, three, two, four, seven, six, seven, eight, nine, seven, six, four, three, seven, six. Lock.",
    "Prune juice...a warrior's drink!",
    "I'm awaiting inspiration...",
    "Windows 7 was my idea!",
    "great job!",
    "What's a computer?",
    "We're turning your bedroom back into the computer room...",
    "Somehow Palpatine Returned!",
    "I don't like sand. It's coarse and rough and irritating and it gets everywhere",
    "Cue 'Curb Your Enthusiasm' theme",
    "@grok is this true?",
    "FAT32!",
    "The geese are free, you can just take them home...",
    "sea shanty2",
    "HACK THE PLANET!",
];