const quotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Don't forget to thank the bus driver",
  "If someone brags, brag right back",
  '<a href="https://www.google.com/search?q=superb+owl">superb owl</a>',
  "my code is better than yours",
  '<a href="https://mastodon.social/@Excuse_haver/103519007663114553">Now, topologically, a dog is a sphere</a>',
  '<a href="https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks">Why cant Nelly The Hamster use webhooks?????</a>',
  "we do caches by lines",
  "everything u think, WRONG!",
  "You pushed the America button",
  '<a href="https://www.apollo21.io/transmissions/yes-you-can-launch-a-startup-without-knowing-how-to-code">One of the requirements to start a startup is having no knowledge of code</a>',
  '<a href="https://www.youtube.com/watch?v=KPKzGagdvNc">Water from the nile</a>',
  '<a href="https://cultofthepartyparrot.com">why does my slack channel not have party parrot?</a>',
  '<a href="https://buttondown.com/hillelwayne/archive/did-brendan-eich-really-make-javascript-in-10-days/">javascript was built in a day</a>',
  "I'm not a robot",
  'Sometimes you gotta close a door to open a window',
  '<a href="https://www.linkedin.com/in/apaxq/">somebody hire me already!</a>',
  "so what does your bedrock look like?",
  "Remember to wear sunscreen",
  "I know a guy",
  "Look at all those kings!",
  "i'm gonna have to bench on this thought",
  '<a href="https://careers.nike.com">CHANGE NIKE, CHANGE WALLSTREET, CHANGE THE WORLD!</a>',
  "I own Top Gun on DVD do not mess with me",
  'Get <a href="https://www.stallman.org">Stallman</a> on the phone',
  '<a href="https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fkg5zwmj03bb31.jpg">teach him to do nothing but Naruto run</a>',
  '<a href="https://www.youtube.com/watch?v=q6HN20vX7Go">i&apos;m eating pizza roles rn</a>',
  "instagram in the middle attack",
  "button your god damn shirt up!",
  "Push START to open the MENU!",
  '<a href="https://www.youtube.com/watch?v=rQZK858Xuag">i need the electrolytes for my tantrums</a>',
  "C++ with Bob Ross",
  '<a href="https://en.wikipedia.org/wiki/Test-driven_development">You know I&apos;m down with TDD</a>',
  "The worlds greatest artist are on RCA Victor Records",
  '<a href="https://www.youtube.com/watch?v=ccMYgiSC_eQ">All the nightmares came today, And it looks as though they&apos;re here to stay</a>',
  '<a href="https://www.youtube.com/watch?v=rtL5oMyBHPs">If you get out of bed, And find me standing all alone, Open-eyed, Burn the page, My little dark age</a>',
  '<a href="https://www.youtube.com/watch?v=tmozGmGoJuw">Don&apos;t you have somewhere to be at seven thirty?</a>',
  "I personally wouldn't use Ruby to pilot a spacecraft",
  "The correct spelling is SCHOOL, not SCHOOL. Some people put the second O before the first O which is absolutely wrong.",
  "We live in a JRPG",
  "Java is the gateway to hell",
  '<a href="https://www.youtube.com/watch?v=3M8m6GllnG8">I hear channel 62 is pretty good</a>',
  '<a href="https://www.facebook.com/61550036493507/videos/billburr-married-life-humor-standup-standupcomedy-standupcomedian-fyp-billburr-b/560211580254503/">One step closer to my own personal hell!</a>',
  '<a href="https://www.youtube.com/watch?v=OpThntO9ixc">weapons was good</a>',
  "Do not operate with wet hands",
  '<a href="https://github.com/madelk/Gerstboard/blob/master/Prepare%20for%20multiballl.mp3">All hand prepare for multi-ball!</a>',
  '<a href="https://www.youtube.com/watch?v=cFods1KSWsQ">Fascinating!</a>',
  "Hailing frequencies open, Captain.",
  '<a href="https://www.youtube.com/watch?v=MULMbqQ9LJ8">I&apos;m a doctor, not a scriptwriter!</a>',
  '<a href="https://www.youtube.com/watch?v=wh-_y-c7P8o">Queen to Queen&apos;s level three?</a>',
  '<a href="https://www.youtube.com/watch?v=rERApU26PcA">One, seven, three, four, six, seven, three, two, one, four, seven, six, Charlie, three, two, seven, eight, nine, seven, seven, seven, six, four, three, Tango, seven, three, two, Victor, seven, three, one, one, seven, eight, eight, eight, seven, three, two, four, seven, six, seven, eight, nine, seven, six, four, three, seven, six. Lock.</a>',
  '<a href="https://www.youtube.com/watch?v=3SZ8H52p0Zk">Prune juice...a warrior&apos;s drink!</a>',
  '<a href="https://www.youtube.com/watch?v=gamEwbXcyVw">I&apos;m awaiting inspiration...</a>',
  '<a href="https://www.youtube.com/watch?v=lQQcYYzwxuk">Windows 7 was my idea!</a>',
  'great job!',
  '<a href="https://www.youtube.com/watch?v=3S5BLs51yDQ">What&apos;s a computer?</a>',
  '<a href="https://www.youtube.com/watch?v=b7HlegQjcP4">We&apos;re turning your bedroom back into the computer room...</a>',
  '<a href="https://www.youtube.com/watch?v=EsjwVu_ihKU">Somehow Palpatine returned</a>',
  '<a href="https://www.youtube.com/watch?v=2tLf1JO5bvE">I don&apos;t like sand. It&apos;s coarse and rough and irritating and it gets everywhere</a>',
  'Cue &apos;<a href="https://www.youtube.com/watch?v=Ag1o3koTLWM">Curb Your Enthusiasm</a>&apos; theme',
  '<a href="https://pbs.twimg.com/media/Gv4gYOrWkAAsUdh?format=jpg&name=4096x4096">@grok is this real?</a>',
  '<a href="https://www.youtube.com/watch?v=eKYj6E-L01g">FAT32!</a>',
  "The geese are free, you can just take them home...",
  '<a href="https://www.youtube.com/watch?v=BJhF0L7pfo8">sea shanty2</a>',
  '<a href="https://www.youtube.com/watch?v=u3CKgkyc7Qo">HACK THE PLANET!</a>',
  "Sargent, dial the Stargate!",
  '<a href="https://www.youtube.com/watch?v=Zp_EhjlLGkQ">It&apos;s a cookbook!</a>',
  'sometimes I open chip bags upside down',
  'My server is offline',
  '<a href="https://nosystemd.org">If this is the solution, I want my problem back!</a>',
  '<a href="https://www.youtube.com/watch?v=vUJTemgaqjI">I just had two cookies and a coke, That&apos;s phenomenal!</a>',
  '<a href="https://en.uncyclopedia.co/wiki/C%2B%2B#History">c++ is an obese, diseased rat named Keith, whose hind leg is missing because it was blown off.</a>',
  '<a href="https://www.youtube.com/watch?v=58dZ9euVx-c">Welcome to the Fantasy Zone! Get Ready!</a>',
  '<a href="https://www.youtube.com/watch?v=GPMFpAJIWcs">Substitute, here we go!</a>',
  'it almost worked after a few hours',
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  'I don\'t really find the giant chicken in Family Guy very funny',
  'bark bark woof arf wruff woof :3 haiiii~ <3',
  '<a href="https://i.kym-cdn.com/photos/images/original/002/963/054/37d">Well, would you look at the time</a>',
  'ska came before reggae',
  'When a measure becomes a target, it ceases to be a good measure.',
  '<a href="https://www.gnu.org/gnu/incorrect-quotation.en.html">I&apos;d just like to interject for a moment. What you’re refering to as Linux, is in fact, GNU/LInux, or as I&apos;ve recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX. Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called "Linux", and many of its users are not aware that it is basically the GNU system, developed by the GNU Project.There really is a Linux, and these people are using it, but it is just a part of the system they use. Linux is the kernel: the program in the system that allocates the machine&apos;s resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. Linux is normally used in combination with the GNU operating system: the whole system is basically GNU with Linux added, or GNU/Linux. All the so-called "Linux" distributions are really distributions of GNU/Linux.</a>',
  'Unix Wars - Episode V: AT&T Strikes Back',
  '<a href="https://igwiki.lyci.de/wiki/Backups">Computer users fall into two groups: those that do backups, and those that have never had a hard drive fail.</a>'
];